plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.2' // 4.1.0에서 안정적인 3.x 버전으로 수정
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'sbb project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Web, JPA, H2
	implementation 'org.springframework.boot:spring-boot-starter-web' // webmvc 대신 표준 starter-web 사용
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa' 
	runtimeOnly 'com.h2database:h2'

	// Lombok
	compileOnly 'org.projectlombok:lombok' 
	annotationProcessor 'org.projectlombok:lombok'

	// Devtools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test' // webmvc-test 대신 전체 기능 제공하는 starter-test 사용
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter' 
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	// tymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'
    
    // validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    
    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    
    // markdown
    implementation 'org.commonmark:commonmark:0.21.0'

}

tasks.named('test') {
	useJUnitPlatform()
}
